### PR TITLE
Added code for dsu ds

### PR DESCRIPTION
**Pull request by i-m-arin**

### CODE REVIEW

**Review by debojeetjha10 — CHANGES_REQUESTED** [review]
put the binary search algo inside a `cpp/binary_search` folder.
and fix the header files don't use
 ```cpp
#include <bits/stdc++.h>
```
it unneccesariliy imports a lot of stuff that is unused during the program. and consumes system memory while running after compilation.

**Comment by debojeetjha10** [comment]
@i-m-arin  please make the necessary changes,......so that I can merge it into the master.

**Comment by i-m-arin** [comment]
Check now whether everything is fine or not.

**Review by debojeetjha10 — APPROVED** [review]
good but do this for the `dsu.cpp` also and try to put them in a folder

**Pull request closed without merging**
