### PR TITLE
Sum of even and odd Array separately.

### PR DESCRIPTION
**Pull request by Madmaxcoder2612**

### CODE REVIEW

**Review by debojeetjha10 — CHANGES_REQUESTED** [review]
delete the ```EVEN ODD SUM ARRAY.cpp``` file in the main folder.

**Comment by Madmaxcoder2612** [comment]
deleted the old file.

**Comment by rishab1128** [comment]
@Madmaxcoder2612 you have still not changed the extension of your file to ```.c``` .Change it and add it into the ```Algorithms``` folder under the ```c``` folder, try to maintain a proper heirarchy and if you want to add a ```.cpp``` file then add into the respective folders maintained under CPP

**Review by debojeetjha10 — APPROVED** [review]

**Comment by debojeetjha10** [comment]
@Madmaxcoder2612 exclude 
```cpp
#include <conio.h>
```
as that is os specific try to code that can be used in any os as long as possible.
i reverted your pr please change that and send a pr again.

**Pull request merged**
